apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-net-ca-tools
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: carrier-net-ca-tools
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-catools
  values:
    metadata:
      namespace: carrier-net
      name: ca-tools
      component_type: peer
      org_name: carrier
      proxy: haproxy
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    replicaCount: 1

    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      catools: ghcr.io/hyperledger/bevel-fabric-ca-tools:1.2.1
      pullPolicy: IfNotPresent
    
    storage:
      storageclassname: carrier-minikube-storageclass
      storagesize: 512Mi
    
    vault:
      role: vault-role
      address: http://45.32.121.191:8200
      authpath: localcarrier-net-auth
      secretusers: secretsv2/data/crypto/peerOrganizations/carrier-net/users
      secretorderer: secretsv2/data/crypto/peerOrganizations/carrier-net/orderers
      secretpeer: secretsv2/data/crypto/peerOrganizations/carrier-net/peers
      secretpeerorderertls: secretsv2/data/crypto/peerOrganizations/carrier-net/orderer/tls
      secretcert: secretsv2/data/crypto/peerOrganizations/carrier-net/ca?ca.carrier-net-cert.pem
      secretkey: secretsv2/data/crypto/peerOrganizations/carrier-net/ca?carrier-net-CA.key
      secretcouchdb: secretsv2/data/credentials/carrier-net/couchdb/carrier
      secretconfigfile: secretsv2/data/crypto/peerOrganizations/carrier-net/msp/config
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
    
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2

    
    org_data:
      external_url_suffix: svc.cluster.local
      component_subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      cert_subject: O=Carrier/OU=Carrier/L=51.50,-0.13,London/C=GB
      component_country: GB
      component_state: London
      component_location: London
      ca_url: ca.carrier-net.svc.cluster.local:7054

    orderers:
      name: orderer1-orderer2-orderer3-
    orderers_info:
      - name: orderer1
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNKRENDQWNxZ0F3SUJBZ0lVVm5IVmJJUEs3QmpzeVN3TE0zSzBYbjJRNnJZd0NnWUlLb1pJemowRUF3SXcKY0RFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUzB3S3dZRFZRUUREQ1JqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF1CmMzWmpMbU5zZFhOMFpYSXViRzlqWVd3d0hoY05NalF3TVRFNE1Ea3lOVEExV2hjTk1qWXhNVEEzTURreU5UQTEKV2pCd01Rc3dDUVlEVlFRR0V3SkhRakVQTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1awpiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnlaWEl4TFRBckJnTlZCQU1NSkdOaExuTjFjSEJzZVdOb1lXbHVMVzVsCmRDNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJLTkwKL09jSDVKdXA3SEkvaWZXVVRMSlhnNlRXR3M3RDJzcWd0ZFFWY2dWM2dLTlVhRzdCalRzWGR4MVpGTHJkc29sZAp0SWQveEpsajR3VnZEOHV0dTNxalFqQkFNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFECkFnR21NQjBHQTFVZERnUVdCQlRUUEJVaURpSythb01QK1VLV0l4NnVGUHk5R0RBS0JnZ3Foa2pPUFFRREFnTkkKQURCRkFpRUE0TnB2YURaZkVZUG4yWHVGZkdLZ2NwZjgrMDY1Y2RseUpmSlE3ZHQ0SHhrQ0lHZGgwYnRwanRkbwprck5OSlJhRGV3SytOOHU4bjRzZzdHMCtUSHVUd09abwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
      - name: orderer2
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNKRENDQWNxZ0F3SUJBZ0lVVm5IVmJJUEs3QmpzeVN3TE0zSzBYbjJRNnJZd0NnWUlLb1pJemowRUF3SXcKY0RFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUzB3S3dZRFZRUUREQ1JqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF1CmMzWmpMbU5zZFhOMFpYSXViRzlqWVd3d0hoY05NalF3TVRFNE1Ea3lOVEExV2hjTk1qWXhNVEEzTURreU5UQTEKV2pCd01Rc3dDUVlEVlFRR0V3SkhRakVQTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1awpiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnlaWEl4TFRBckJnTlZCQU1NSkdOaExuTjFjSEJzZVdOb1lXbHVMVzVsCmRDNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJLTkwKL09jSDVKdXA3SEkvaWZXVVRMSlhnNlRXR3M3RDJzcWd0ZFFWY2dWM2dLTlVhRzdCalRzWGR4MVpGTHJkc29sZAp0SWQveEpsajR3VnZEOHV0dTNxalFqQkFNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFECkFnR21NQjBHQTFVZERnUVdCQlRUUEJVaURpSythb01QK1VLV0l4NnVGUHk5R0RBS0JnZ3Foa2pPUFFRREFnTkkKQURCRkFpRUE0TnB2YURaZkVZUG4yWHVGZkdLZ2NwZjgrMDY1Y2RseUpmSlE3ZHQ0SHhrQ0lHZGgwYnRwanRkbwprck5OSlJhRGV3SytOOHU4bjRzZzdHMCtUSHVUd09abwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
      - name: orderer3
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNKRENDQWNxZ0F3SUJBZ0lVVm5IVmJJUEs3QmpzeVN3TE0zSzBYbjJRNnJZd0NnWUlLb1pJemowRUF3SXcKY0RFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUzB3S3dZRFZRUUREQ1JqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF1CmMzWmpMbU5zZFhOMFpYSXViRzlqWVd3d0hoY05NalF3TVRFNE1Ea3lOVEExV2hjTk1qWXhNVEEzTURreU5UQTEKV2pCd01Rc3dDUVlEVlFRR0V3SkhRakVQTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1awpiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnlaWEl4TFRBckJnTlZCQU1NSkdOaExuTjFjSEJzZVdOb1lXbHVMVzVsCmRDNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJLTkwKL09jSDVKdXA3SEkvaWZXVVRMSlhnNlRXR3M3RDJzcWd0ZFFWY2dWM2dLTlVhRzdCalRzWGR4MVpGTHJkc29sZAp0SWQveEpsajR3VnZEOHV0dTNxalFqQkFNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFECkFnR21NQjBHQTFVZERnUVdCQlRUUEJVaURpSythb01QK1VLV0l4NnVGUHk5R0RBS0JnZ3Foa2pPUFFRREFnTkkKQURCRkFpRUE0TnB2YURaZkVZUG4yWHVGZkdLZ2NwZjgrMDY1Y2RseUpmSlE3ZHQ0SHhrQ0lHZGgwYnRwanRkbwprck5OSlJhRGV3SytOOHU4bjRzZzdHMCtUSHVUd09abwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

    peers:
      name: peer0,-      
    peer_count: "1"
    users: 
      users_list: "W3sndXNlcic6IE5vbmUsICdpZGVudGl0eSc6ICd1c2VyMScsICdhdHRyaWJ1dGVzJzogW3sna2V5JzogJ2hmLlJldm9rZXInLCAndmFsdWUnOiAndHJ1ZSd9XX1d"
      users_identities: user1-
    checks:
      refresh_cert_value: False
      add_peer_value: False
