apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: store-net-ca-tools
  namespace: store-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: store-net-ca-tools
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-catools
  values:
    metadata:
      namespace: store-net
      name: ca-tools
      component_type: peer
      org_name: store
      proxy: none
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    replicaCount: 1

    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      catools: ghcr.io/hyperledger/bevel-fabric-ca-tools:1.2.1
      pullPolicy: IfNotPresent
    
    storage:
      storageclassname: store-minikube-storageclass
      storagesize: 512Mi
    
    vault:
      role: vault-role
      address: http://45.32.121.191:8200
      authpath: localstore-net-auth
      secretusers: secretsv2/data/crypto/peerOrganizations/store-net/users
      secretorderer: secretsv2/data/crypto/peerOrganizations/store-net/orderers
      secretpeer: secretsv2/data/crypto/peerOrganizations/store-net/peers
      secretpeerorderertls: secretsv2/data/crypto/peerOrganizations/store-net/orderer/tls
      secretcert: secretsv2/data/crypto/peerOrganizations/store-net/ca?ca.store-net-cert.pem
      secretkey: secretsv2/data/crypto/peerOrganizations/store-net/ca?store-net-CA.key
      secretcouchdb: secretsv2/data/credentials/store-net/couchdb/store
      secretconfigfile: secretsv2/data/crypto/peerOrganizations/store-net/msp/config
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: ""
    
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2

    
    org_data:
      external_url_suffix: svc.cluster.local
      component_subject: O=Store,OU=Store,L=40.73/-74/New York,C=US
      cert_subject: O=Store/OU=Store/L=40.73,-74,New York/C=US
      component_country: US
      component_state: New York
      component_location: New York
      ca_url: ca.store-net:7054

    orderers:
      name: orderer1-orderer2-orderer3-
    orderers_info:
      - name: orderer1
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVENDQWFhZ0F3SUJBZ0lVY2NMU3hIL1lieXpObC9EOFNZVi9zZC9FU0FVd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NalF3TVRFNE1UWTFNVEUwV2hjTk1qWXhNVEEzTVRZMU1URTBXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJGOWdBaFZRc0tGaVlqU0VLZ2ZaUndwT1RtbTFwR0dVdnBSMU9POTZndE9NTjBoREFQSjAKdjBYbnlxbnZ5cHZjdlRNWVQ5enpvQzRueUx2ckVQNlJ6eWlqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUjV5ZUsxMFZQaVd5bWZkVmFqRU5kclZJbkQwekFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXFGYmI0NlVLRGNBUXNBbldxbUN2cHF3KzJaY0prb25xbnVUVnpleTMKaFhFQ0lRQ2RiN21jOFZuQXJMcVF4U1RvamsvVExjdlBwdHArUDFNbkNKU0ZiVmtUdWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
      - name: orderer2
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVENDQWFhZ0F3SUJBZ0lVY2NMU3hIL1lieXpObC9EOFNZVi9zZC9FU0FVd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NalF3TVRFNE1UWTFNVEUwV2hjTk1qWXhNVEEzTVRZMU1URTBXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJGOWdBaFZRc0tGaVlqU0VLZ2ZaUndwT1RtbTFwR0dVdnBSMU9POTZndE9NTjBoREFQSjAKdjBYbnlxbnZ5cHZjdlRNWVQ5enpvQzRueUx2ckVQNlJ6eWlqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUjV5ZUsxMFZQaVd5bWZkVmFqRU5kclZJbkQwekFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXFGYmI0NlVLRGNBUXNBbldxbUN2cHF3KzJaY0prb25xbnVUVnpleTMKaFhFQ0lRQ2RiN21jOFZuQXJMcVF4U1RvamsvVExjdlBwdHArUDFNbkNKU0ZiVmtUdWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
      - name: orderer3
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVENDQWFhZ0F3SUJBZ0lVY2NMU3hIL1lieXpObC9EOFNZVi9zZC9FU0FVd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NalF3TVRFNE1UWTFNVEUwV2hjTk1qWXhNVEEzTVRZMU1URTBXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJGOWdBaFZRc0tGaVlqU0VLZ2ZaUndwT1RtbTFwR0dVdnBSMU9POTZndE9NTjBoREFQSjAKdjBYbnlxbnZ5cHZjdlRNWVQ5enpvQzRueUx2ckVQNlJ6eWlqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUjV5ZUsxMFZQaVd5bWZkVmFqRU5kclZJbkQwekFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXFGYmI0NlVLRGNBUXNBbldxbUN2cHF3KzJaY0prb25xbnVUVnpleTMKaFhFQ0lRQ2RiN21jOFZuQXJMcVF4U1RvamsvVExjdlBwdHArUDFNbkNKU0ZiVmtUdWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

    peers:
      name: peer0,-      
    peer_count: "1"
    users: 
      users_list: "W3sndXNlcic6IE5vbmUsICdpZGVudGl0eSc6ICd1c2VyMScsICdhdHRyaWJ1dGVzJzogW3sna2V5JzogJ2hmLlJldm9rZXInLCAndmFsdWUnOiAndHJ1ZSd9XX1d"
      users_identities: user1-
    checks:
      refresh_cert_value: False
      add_peer_value: False
